### ISSUE TITLE
Add calculation method - JAKIM  for malaysia

### ISSUE THREAD

**Issue by mansurimohib** [mestery69/prayer-times#1]
Hi,
Please add JAKIM (Jabatan Kemajuan Islam Malaysia) calculation method with params: { fajr: 20, isha: 18 } .

for more info, please this.
https://www.e-solat.gov.my/index.php

**Comment by mestery69** [comment]
I will add it for the next update, however you can use custom settings or add yourself this calculation method to your instance.

```js
let prayer = new PrayerTimes();
prayer.adjust({ fajr: 20, isha: 18 });
```
or
```js
let prayer = new PrayerTimes();
prayer.methods.JAKIM = {
  name: 'Jabatan Kemajuan Islam Malaysia',
  params: { fajr: 20, isha: 18 }
};
prayer.method = 'JAKIM';
```

**Comment by mestery69** [comment]
Done✅

**Comment by mansurimohib** [comment]
> 
> 
> I will add it for the next update, however you can use custom params or add yourself this calculation method to your instance.
> 
> ```js
> let prayer = new PrayerTimes();
> prayer.adjust({ fajr: 20, isha: 18 });
> ```
> 
> or
> 
> ```js
> let prayer = new PrayerTimes();
> prayer.methods.JAKIM = {
>   name: 'Jabatan Kemajuan Islam Malaysia',
>   params: { fajr: 20, isha: 18 }
> };
> prayer.method = 'JAKIM';
> ```

Yes, I have used the same. These JAKIM params are also not showing same time, we have to tune few mins in all prayer. 

Thanks for adding.

**Comment by mestery69** [comment]
Yes☪️🙏🤲
