### ISSUE TITLE
Is this official from praytimes.org?

### ISSUE THREAD

**Issue by Noitidart** [mestery69/prayer-times#2]
Thanks for maintaining this! Is it official and latest from http://praytimes.org/wiki/Code_ChangeLog ?

If they update there would we get it here?

**Comment by mestery69** [comment]
No this isn't the official. This is just a remake of latest version from http://praytimes.org/wiki/Code_ChangeLog

**Comment by Noitidart** [comment]
Barakallahfik brother!
